export const INIT_EXPENSE = 'INIT_EXPENSE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const GET_EXPENSE = 'GET_EXPENSE';
export const UPDATE_FIELD = 'UPDATE_FIELD';